# --- Configuration de base de l'agent ---
agentaddress udp:0.0.0.0:161
rocommunity public
persistentDir /var/net-snmp

sysLocation    IUT Colmar Lab (Simulated)
sysDescr "Cisco - Simulated"
sysContact     YOUR NAME
sysName        cisco-ios-sim-48G
override .1.3.6.1.4.1.9.9.109.1.1.1.1.5 integer 1

override .1.3.6.1.2.1.31.1.1.1.1 interger my-interface1
override .1.3.6.1.2.1.31.1.1.1.2 interger my-interface2
override .1.3.6.1.2.1.31.1.1.1.3 interger my-interface3

pass_persist .1.3.6.1.2.1.2        /usr/local/bin/iut_colmar_passpersist.py
pass_persist .1.3.6.1.2.1.31.1     /usr/local/bin/iut_colmar_passpersist.py
dontLogTCPWrappers yes
